### ISSUE TITLE
Proxy engage issue in Windows environment

### ISSUE THREAD

**Issue by marciogoulart** [hash3liZer/Proxverter#5]
Hello,

I am facing a problem when performing proxy engage. Running in a Windows environment.

Traceback (most recent call last):
  File "teste.py", line 3, in <module>
    prox.engage()
  File "C:\Python38\lib\site-packages\proxverter\__init__.py", line 137, in engage
    proxy.main(
TypeError: main() takes 0 positional arguments but 1 was given

Code:
import proxverter
prox = proxverter.Proxverter(ip="127.0.0.1", port=8081, verbose=True)
prox.engage()

**Comment by hash3liZer** [comment]
Hi, @marciogoulart it seems that the library `proxy.py` has been updated to no longer accept the parameters with the `main` function. I'll try to update it as soon as possible. Thanks.

**Comment by redsigma** [comment]
This issue happens when using proxy.py 2.4.0 and higher. If I use proxy.py version 2.3.1 then it works.
